# Generated by Django 6.1.1 on 2026-09-05 06:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('company', models.CharField(default='Tech Solutions Inc', max_length=150)),
                ('location', models.CharField(default='Remote / Chennai', max_length=150)),
                ('department', models.CharField(default='Core Product Engineering', max_length=150)),
                ('experience', models.CharField(default='2–4 Years Experience', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('target_level', models.IntegerField(default=3)),
                ('reason', models.CharField(max_length=255)),
                ('course_title', models.CharField(blank=True, default='', max_length=255)),
                ('provider', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'recommendations',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='target_title',
            field=models.CharField(default='Java Full Stack Developer', max_length=150),
        ),
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('required_level', models.IntegerField(default=3)),
                ('mandatory', models.BooleanField(default=True)),
                ('category', models.CharField(default='Technical', max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='accounts.job')),
            ],
            options={
                'db_table': 'job_requirements',
                'unique_together': {('job', 'skill_name')},
            },
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('proficiency_level', models.IntegerField(default=1)),
                ('proficiency_tag', models.CharField(default='Beginner', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='accounts.student')),
            ],
            options={
                'db_table': 'student_skills',
                'unique_together': {('student', 'skill_name')},
            },
        ),
    ]
